/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import("./components/Auth.vue")["default"]
    Auth0: typeof import('./components/Auth0.vue')['default']
    ChatGpt: typeof import("./components/ChatGpt.vue")["default"]
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    Cli: typeof import("./components/Cli.vue")["default"]
    Dark: typeof import('./components/Dark.vue')['default']
    GithubButton: typeof import('./components/GithubButton.vue')['default']
    GithubRepository: typeof import('./components/GithubRepository.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    PictureUpload: typeof import('./components/PictureUpload.vue')['default']
    ProgressBar: typeof import("./components/ProgressBar.vue")["default"]
    README: typeof import("./components/README.md")["default"]
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchRepos: typeof import('./components/SearchRepos.vue')['default']
    Speech: typeof import("./components/Speech.vue")["default"]
    SpeechToText: typeof import('./components/SpeechToText.vue')['default']
    Sse: typeof import('./components/Sse.vue')['default']
    Synthesis: typeof import("./components/Synthesis.vue")["default"]
    Templates: typeof import('./components/Templates.vue')['default']
    TextToSpeech: typeof import('./components/TextToSpeech.vue')['default']
    TheCounter: typeof import("./components/TheCounter.vue")["default"]
    TheFooter: typeof import("./components/TheFooter.vue")["default"]
    TheInput: typeof import("./components/TheInput.vue")["default"]
    TodoItem: typeof import("./components/TodoItem.vue")["default"]
    Upload: typeof import('./components/Upload.vue')['default']
    Voice: typeof import("./components/Voice.vue")["default"]
    Websocket: typeof import("./components/Websocket.vue")["default"]
    Ws: typeof import('./components/Ws.vue')['default']
  }
}
